# Generated by Django 2.1.4 on 2018-12-19 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='title')),
                ('article_content', models.TextField(verbose_name='content')),
                ('article_pubdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(verbose_name='comment')),
                ('comment_date', models.DateTimeField(verbose_name='date commented')),
                ('comment_father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Comment', verbose_name='father comment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(max_length=20, verbose_name='label')),
                ('tag_description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='name')),
                ('user_password', models.CharField(max_length=50, verbose_name='password')),
                ('user_email', models.EmailField(max_length=254, verbose_name='email')),
                ('user_isadmin', models.BooleanField(verbose_name='isadmin')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User', verbose_name='comment user'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.User', verbose_name='publisher'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(to='Blog.Tag', verbose_name='tags'),
        ),
    ]
