# Generated by Django 2.1.4 on 2018-12-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_label', models.CharField(max_length=20, verbose_name='label')),
                ('class_description', models.CharField(max_length=100, verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='article',
            name='article_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Class', verbose_name='class'),
        ),
    ]
