# Generated by Django 2.1.4 on 2018-12-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20181219_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Class', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Comment', verbose_name='father comment'),
        ),
    ]
