# Generated by Django 2.1.4 on 2018-12-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20181220_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='comment article'),
        ),
    ]
