# Generated by Django 2.1.4 on 2018-12-21 02:13

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=mdeditor.fields.MDTextField(verbose_name='content'),
        ),
    ]
