# Generated by Django 2.1.4 on 2018-12-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20181221_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_simpledesc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='simple description'),
        ),
    ]
